name: SimpleWarp
main: at.vailan.simplewarp.SimpleWarp
version: '${project.version}'
api-version: '1.21'
description: Allows teleportation to previously configured warp points
author: '${project.author}'

commands:
  warp:
    description: Teleport to a warp point
    usage: /warp [warpName]
    aliases:
      - w
    permission: simplewarp.use

  setwarp:
    description: Create a warp point
    usage: /setwarp [warpName]
    permission: simplewarp.set

  deletewarp:
    description: Delete a warp point
    usage:  /deletewarp [warpName]
    aliases:
      - delwarp
    permission: simplewarp.delete

permissions:
  simplewarp.*:
    description: Gives access to all SimpleWarp features
    children:
      simplewarp.use: true
      simplewarp.set: true
      simplewarp.delete: true
      simplewarp.execute: true
    default: op

  simplewarp.admin:
    description: Gives access to all SimpleWarp features
    children:
      simplewarp.use: true
      simplewarp.set: true
      simplewarp.delete: true
      simplewarp.execute: true
    default: op

  simplewarp.use:
    description: Allows using warps
    default: true

  simplewarp.set:
    description: Allows creating warps
    default: op

  simplewarp.delete:
    description: Allows deleting warps
    default: op

  simplewarp.execute:
    description: Allows teleporting other players to warps
    default: op